//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_applications
    {
        public int application_id { get; set; }
        public int id_party { get; set; }
        public int id_user { get; set; }
        public System.DateTime apply_date { get; set; }
        public string status { get; set; }
        public string motivation { get; set; }
    
        public virtual parties parties { get; set; }
        public virtual users users { get; set; }
    }
}
