//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_budgets
    {
        public int budget_id { get; set; }
        public int id_party { get; set; }
        public int year { get; set; }
        public decimal amount { get; set; }
        public decimal spent { get; set; }
    
        public virtual parties parties { get; set; }
    }
}
