//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_partners
    {
        public int partner_id { get; set; }
        public int id_party { get; set; }
        public string partner_name { get; set; }
        public string partner_type { get; set; }
        public Nullable<System.DateTime> since_date { get; set; }
    
        public virtual parties parties { get; set; }
    }
}
