//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_events
    {
        public int event_id { get; set; }
        public int id_party { get; set; }
        public string event_name { get; set; }
        public System.DateTime event_date { get; set; }
        public string location { get; set; }
        public string description { get; set; }
    
        public virtual parties parties { get; set; }
    }
}
