//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_equipment
    {
        public int equipment_id { get; set; }
        public int id_party { get; set; }
        public string item_name { get; set; }
        public int quantity { get; set; }
        public string condition { get; set; }
    
        public virtual parties parties { get; set; }
    }
}
