//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<club_achievements> club_achievements { get; set; }
        public virtual DbSet<club_applications> club_applications { get; set; }
        public virtual DbSet<club_budgets> club_budgets { get; set; }
        public virtual DbSet<club_equipment> club_equipment { get; set; }
        public virtual DbSet<club_events> club_events { get; set; }
        public virtual DbSet<club_partners> club_partners { get; set; }
        public virtual DbSet<club_publications> club_publications { get; set; }
        public virtual DbSet<club_schedules> club_schedules { get; set; }
        public virtual DbSet<club_votings> club_votings { get; set; }
        public virtual DbSet<parliament_compositions> parliament_compositions { get; set; }
        public virtual DbSet<parties> parties { get; set; }
        public virtual DbSet<parties_in_parliament> parties_in_parliament { get; set; }
        public virtual DbSet<party_members> party_members { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<seats_list> seats_list { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
