//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class parliament_compositions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parliament_compositions()
        {
            this.seats_list = new HashSet<seats_list>();
            this.parties_in_parliament = new HashSet<parties_in_parliament>();
        }
    
        public int id_composition { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> id_council_chair { get; set; }
        public Nullable<int> id_chair_corps1 { get; set; }
        public Nullable<int> id_chair_corps2 { get; set; }
        public Nullable<int> id_chair_corps3 { get; set; }
        public Nullable<int> id_chair_corps4 { get; set; }
        public Nullable<int> id_chair_corps5 { get; set; }
        public Nullable<int> id_chair_corps6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seats_list> seats_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parties_in_parliament> parties_in_parliament { get; set; }
    }
}
