//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public party_members()
        {
            this.seats_list = new HashSet<seats_list>();
        }
    
        public int id_member { get; set; }
        public int id_user { get; set; }
        public int id_party { get; set; }
        public string position { get; set; }
        public System.DateTime join_date { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public string status { get; set; }
    
        public virtual parties parties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seats_list> seats_list { get; set; }
        public virtual users users { get; set; }
    }
}
