//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlamentSS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class parties_in_parliament
    {
        public int id_record { get; set; }
        public int id_composition { get; set; }
        public int id_party { get; set; }
        public int seats_count { get; set; }
    
        public virtual parliament_compositions parliament_compositions { get; set; }
        public virtual parties parties { get; set; }
    }
}
