//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1zadan.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredients
    {
        public int idRecipeIngredients { get; set; }
        public Nullable<int> idRecipe { get; set; }
        public Nullable<int> idIngredient { get; set; }
        public string quality { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
