//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1zadan.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int idReview { get; set; }
        public Nullable<int> idRecipe { get; set; }
        public string reviewText { get; set; }
        public string rating { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
